#!/usr/bin/env bash
# displays Best School 10 times using until.

x=0 
until false; do
	echo "Best School"
	  ((x++))
	    if [[ $x -lt 10 ]]; then
			 continue
				 else
					break
					 fi
				done
