#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 

x=1
while [ "$x" -lt 11 ]; do
	    # if the value is 4:bad luck 
	        if [ "$x" -eq 4 ]; then
			        echo "bad luck"
				    elif [ "$x" -eq 8 ]; then 
					            echo "good luck"
						        else
							       echo "Best School"
									    fi
									        ((x++))
									done
