#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20

x=1
while [ "$x" -lt 21 ]; do
	 # if the value is 4:bad luck
	 case "$x" in
		 4)
			 echo "$x"
			 echo "bad luck from China"
			 ;;
		 9)    	 echo "$x"
			 echo "bad luck from Japan"
			 ;;
	        17) 	echo "$x"
			echo "bad luck from Italy"
			;;
		*)
			echo "$x"
			;;
		esac

		((x++))
done
