#!/usr/bin/env bash
# a script that displays: to infinity and beyond indefinitely with a sleep 2 in between each iteration I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while true;
do
	  echo "To infinity and beyond"
	  sleep 2
done 
